### ISSUE TITLE
Ability to download levels via ID Lookup (v1.0)

### ISSUE THREAD

**Issue by Voksius** [XyphosChord/GeoBrowser#1]
Add an option to the menu that will try to download the level and if it fails, it will display all info possible without downloading.

**Comment by Voksius** [comment]
I made a pull request [here](https://github.com/XyphosChord/GeoBrowser/pull/2) that adds an option download level info, but I haven't been able to test it since the code was written on a school chromebook that has every online IDE blocked :/

**Comment by XyphosChord** [comment]
Merged both of your pull requests. Thanks for helping :)
